### ISSUE TITLE
Add support for SQL store

### ISSUE THREAD

**Issue by wallyqs** [nats-io/nats-streaming-operator#10]
```
Streaming Server SQL Store Options:
    --sql_driver <string>            Name of the SQL Driver ("mysql" or "postgres")
    --sql_source <string>            Datasource used when opening an SQL connection to the database
    --sql_no_caching <bool>          Enable/Disable caching for improved performance
    --sql_max_open_conns <int>       Maximum number of opened connections to the database
```

**Comment by juandiegopalomino** [comment]
@wallyqs hi there-- NATS Streaming looks awesome and I was wondering if there's any development on this issue (or the operator in general) going on at the moment.

**Comment by wallyqs** [comment]
Hi @juandiegopalomino yes planning to release some updates this month related to this, are you looking at a certain store in particular?

**Comment by IsmailMarmoush** [comment]
Hello @wallyqs , Is there a plan for Scylla DB ? how is it possible to extend such API ? any docs would be helpful.

**Comment by juandiegopalomino** [comment]
@wallyqs any update on the status of this issue?
