### ISSUE TITLE
Run on different namespace

### ISSUE THREAD

**Issue by Shadowfaxenator** [nats-io/nats-streaming-operator#3]
Is it ok to ask operator to run NATS and STUN on a different namespace than operator runs on?

**Comment by wallyqs** [comment]
STAN/NATS Streaming servers will be created on the same namespace as the NATS Streaming operator, but should be possible to connect to a NATS service running on a different namespace via the `natsSvc` option.

**Comment by shaxbee** [comment]
It would be beneficial if operator could pick up stan resources outside its namespace.

**Comment by wallyqs** [comment]
Possible for the nats and nats-streaming servers services to be on different namespaces, just have to specify where the service for nats is located.  For example if running nats-streaming in the default namespace but the nats service is on the `nats-io` namespace, then in the manifest have to point to the name of the service and the namespace:

```
natsSvc: "example-nats.nats-io"
```
