### ISSUE TITLE
Support for authenticated NATS cluster

### ISSUE THREAD

**Issue by typusomega** [nats-io/nats-streaming-operator#30]
Hi,

we are using an authenticated NATS cluster and are big fans of this operator.
Since the operator is overriding the STAN pods' command, I see no chance to add `--user`/`--pass`.

Is there a way to authenticate `NatsStreamingCluster`s?

Best regards

**Comment by typusomega** [comment]
Hi, 

finally managed to make it work:
Since STAN is using NATS' options, it's possible to mount a config file (in a secret) containing the credentials.

Is this the recommended way to go?

**Comment by wallyqs** [comment]
Yes that approach would recommended in order to handle the credentials as a secret.

**Comment by wallyqs** [comment]
Using the secret for the credentials recommended way for now to avoid leaking creds via crd definitions, env vars, etc... closing for now

**Comment by Upperfoot** [comment]
@wallyqs How exactly was this achieved? I can't find any documentation for this with Kubernetes. I would like to use Service Accounts which have already been set up and are being used by the nats-clusters

**Comment by pja-kit** [comment]
@wallyqs @typusomega 
Could you give an example on how you have achieved this, for me it is not clear how the configFile should created
