### ISSUE TITLE
Helm chart repo

### ISSUE THREAD

**Issue by 4nte** [nats-io/nats-streaming-operator#68]
Helm chart can be hosted via Github pages and chart releases can be automated via Github actions.
Finally the nats-streaming-operator can be added to helm hub for better reach.

I'm glad to help with this.

**Comment by wallyqs** [comment]
Hi you can find some helm charts here for NATS Streaming: https://github.com/nats-io/k8s#helm-charts-for-nats we will submit to helm hub after next release
