### ISSUE TITLE
Version numbering inconsistency, please release again

### ISSUE THREAD

**Issue by sdhoward** [nats-io/nats-streaming-operator#79]
For release `v0.4.0`, the `deployment.yaml` file attached to the [release page](https://github.com/nats-io/nats-streaming-operator/releases/tag/v0.4.0) contains a reference to a docker image called `synadia/nats-streaming-operator:v0.4.0`, which does not exist. Rather, an image called [`synadia/nats-streaming-operator:0.4.0`](https://hub.docker.com/r/synadia/nats-streaming-operator/tags) exists (the v is missing).

Also, the [deployment.yaml](https://github.com/nats-io/nats-streaming-operator/blob/v0.4.0/deploy/deployment.yaml#L34) file located in the repository at the commit which is tagged `v0.4.0` contains a reference to a docker image `synadia/nats-streaming-operator:v0.3.0-v1alpha1`.

You could sort this out by updating the deploy directory before cutting a release, and releasing a v0.4.1 or 0.4.1 release on both github and docker hub once it's consistent.

**Comment by wallyqs** [comment]
Did another release so that the version inconsistency is fixed, thanks for the report: https://github.com/nats-io/nats-streaming-operator/releases/tag/v0.4.2
